version: '3.8'

services:
  # Web Server
  db: # Database service. Install a recent version of SQL Server, define a adm password, mapping the port to connect to db outside the container if we need.
    image: mcr.microsoft.com/mssql/server:2022-latest # Microsoft SQL Server 2022
    container_name: mssql_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Stockya@123456
    ports:
      - "14330:1433" # Expose SQL Server port
    volumes:
      - mssql_data:/var/opt/mssql # Persist SQL Server data

  # Backend ASP.NET Core API
  api: # API service. Define that the API will be builf from Dockerfile in the backend folder and will depend on the database service.
    container_name: webapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=stockya_db
      - DB_SA_PASSWORD=Stockya@123456

volumes:
  mssql_data:
